### PR TITLE
Initial test API

### PR DESCRIPTION
**Pull request by MarcL**
- Mentoring @spences10 and @amandeepmittal by adding some tests to this project for an API using TDD.

### CODE REVIEW

**Comment by amandeepmittal** [comment]
@MarcL Thanks!

**Comment by MarcL** [comment]
@amandeepmittal - I've refactored it a bit and I'll add some more of the API + tests to show you a bit more if you like. Will try and get it done one night this week.

**Comment by spences10** [comment]
Thanks @MarcL 👍

**Comment by amandeepmittal** [comment]
Take your time @MarcL  👍

**Pull request merged**
